version: "3.7"

# x-extension fields
x-env_file: &env_file
  env_file:
    - ./.env


volumes:
  app:
    external: false
  redis:
    external: false

services:
  backend:
    <<: *env_file
    build: .
    ports:
      - 8000:8000
      - 2222:2222  # via Locust
    restart: always
    volumes:
      - ./app/:/app

  redis:
    image: library/redis:6
    <<: *env_file
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
