version: "3.7"

# x-extension fields
x-env_file: &env_file
  env_file:
    - ./.env

x-base: &base
  <<: *env_file
  build: .
  volumes:
    - ./app/:/app

services:
  backend:
    <<: *base
    ports:
      - 8000:8000
    restart: always
