from fastapi import APIRouter

router = APIRouter()

GET_SESSION_DESCRIPTION_OFFER_BASE = "/session-description/offer"
GET_SESSION_DESCRIPTION_OFFER = GET_SESSION_DESCRIPTION_OFFER_BASE + "/{offer_key}"

SET_SESSION_DESCRIPTION_ANSWER_BASE = "/session-description/answer"
SET_SESSION_DESCRIPTION_ANSWER = SET_SESSION_DESCRIPTION_ANSWER_BASE + "/{offer_key}"
