version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.0


executors:
  python:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8

jobs:
  checkout_code:
    executor: python
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  install_requirements:
    executor: python
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "app/requirements/requirements.txt" }}-{{ checksum "app/requirements/dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make update-deps
      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "app/requirements/requirements.txt" }}-{{ checksum "app/requirements/dev.txt" }}

  run_tests:
    executor: python
    docker:
      - image: circleci/python:3.8
        environment:
          SECRET_KEY: test
          DEBUG: True
      - image: redis:6-alpine
        environment:
          REDIS_HOST: 0.0.0.0
          REDIS_PORT: 6379
          REDIS_DB: 0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "app/requirements/requirements.txt" }}-{{ checksum "app/requirements/dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make run-tests
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  upload-to-acr-latest:
    executor: azure-acr/default
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - azure-acr/build-and-push-image:
          login-server-name: $ACR_REGISTRY_LOGIN
          registry-name: $ACR_REGISTRY_NAME
          repo: $ACR_REPOSITORY_NAME
          tag: latest

workflows:
  version: 2.1
  build-and-push-image:
    jobs:
      - checkout_code
      - install_requirements:
          requires:
            - checkout_code
      - run_tests:
          requires:
            - install_requirements

      # no CD for now - it generates costs, leave tests only
#      - upload-to-acr-latest:
#          requires:
#            - run_tests
#          filters:
#            branches:
#              only:
#                - develop
